apiVersion: v1
kind: Service
metadata:
  name: nodejstest-service
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodejstest
  type: NodePort
