apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodejstest
spec:
  replicas: 8
  selector:
    matchLabel:
      app: nodejslatest
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: nodejstest
    spec:     # pod spec                  
      containers: 
      - name: nodejstest
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "250Mi"
        imagePullPolicy: Always
        image: raviarora561/nodejstest:latest # image we pushed
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
      
